# Netlify configuration for MkDocs site

[build]
# Command to build the site: Install MkDocs, then run the build using python -m to ensure it's found
command = "pip install mkdocs && python -m mkdocs build --clean --site-dir _site"
# Directory containing the built site relative to the repository root
publish = "_site"

[build.environment]
# Specify the Python version Netlify should use (e.g., 3.8, 3.11 - check Netlify docs for supported versions)
PYTHON_VERSION = "3.8"

# Disable Netlify's asset processing as MkDocs handles static site generation completely.
# This prevents potential conflicts or unexpected modifications by Netlify's build system.
[build.processing]
skip_processing = true
