project:
  type: website

website:
  title: "Dan's Diner"
  navbar:
    right:
      - text: "Pachecod.github.io"
        href: https://pachecod.github.io
      - blog.qmd
      - icon: github
        href: https://github.com/pachecod
      - icon: twitter
        href: https://twitter.com/pachecod
      - icon: rss
        href: blog.xml
      - text: Archive
        href: archive.qmd

cookie-consent: true      

format:
  html:
    theme: theme.scss

editor: visual

